name: Deploy to S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Required for OIDC
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHubActions-DreamoryWebsite
        aws-region: us-east-1

    - name: Sync to S3 (ap-south-1)
      run: |
        aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude ".git/*" --exclude ".github/*" --region ap-south-1

    - name: Invalidate CloudFront (us-east-1)
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" --region us-east-1
